# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
# no longer need for jekyll 3.0
# relative_permalinks: true

# Setup
title:            Æsop
tagline:          'Austin E Soplata'
description:      'Personal website of <a href="https://github.com/asoplata" target="_blank">Austin Soplata</a>.'
# Was just "/" before 20161012, but redirects to home/main page weren't working
baseurl:

author:
  name:           'Austin Soplata'
  url:            https://github.com/asoplata

# how do i even?
# gems:             [jekyll-paginate]
gems:
  - jekyll-paginate
  - jekyll-feed
paginate:         5

# Custom vars
version:          2.1.0

future:           true

github:
  repo:           https://github.com/asoplata/asoplata.github.io

theme: jekyll-theme-minimal